version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.11"  # use quotes to avoid type issues
  install:
    - method: pip
      path: .
    - requirements: docs/source/requirements.txt
